import os

from research_config import (
    FACTOR_MATRIX_DIR,
    FACTOR_METADATA_PATH,
    PRIMARY_TRANSACTION_COST_BPS,
    PROJECT_ROOT,
    RESEARCH_DATA_DIR,
    RESEARCH_RESULTS_DIR,
    SELECTION_CARDS_PATH,
)


# -------------------------
# PATHS
LOW_VOLATILITY_DATA_DIR = os.path.join(
    RESEARCH_DATA_DIR,
    "Low_Volatility",
)
LOW_VOLATILITY_CACHE_DIR = os.path.join(
    LOW_VOLATILITY_DATA_DIR,
    "Cache",
)
LOW_VOLATILITY_RESULTS_DIR = os.path.join(
    RESEARCH_RESULTS_DIR,
    "Low_Volatility",
)
LOW_VOLATILITY_FIGURES_DIR = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "Figures",
)
LOW_VOLATILITY_PORTFOLIO_METADATA_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "portfolio_metadata.csv",
)
LOW_VOLATILITY_PORTFOLIO_STATISTICS_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "portfolio_statistics.csv",
)
LOW_VOLATILITY_PHASE_STABILITY_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "calendar_phase_stability.csv",
)
LOW_VOLATILITY_WALK_FORWARD_PERIODS_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "walk_forward_periods.csv",
)
LOW_VOLATILITY_WALK_FORWARD_SUMMARY_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "walk_forward_summary.csv",
)
LOW_VOLATILITY_WALK_FORWARD_PATHS_PATH = os.path.join(
    LOW_VOLATILITY_CACHE_DIR,
    "walk_forward_oos_paths.parquet",
)
LOW_VOLATILITY_REGIME_RESULTS_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "regime_performance.csv",
)
LOW_VOLATILITY_FACTOR_OVERLAP_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "factor_overlap.csv",
)
LOW_VOLATILITY_WINDOW_SUMMARY_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "window_summary.csv",
)
LOW_VOLATILITY_BENCHMARK_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "benchmark_statistics.csv",
)
LOW_VOLATILITY_SECTOR_STATUS_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "sector_exposure_status.csv",
)
LOW_VOLATILITY_REPORT_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "low_volatility_report.md",
)
LOW_VOLATILITY_RUN_METADATA_PATH = os.path.join(
    LOW_VOLATILITY_RESULTS_DIR,
    "run_metadata.json",
)
LOW_VOLATILITY_CACHE_MANIFEST_PATH = os.path.join(
    LOW_VOLATILITY_CACHE_DIR,
    "cache_manifest.json",
)


# -------------------------
# RESEARCH DESIGN
LOW_VOLATILITY_WINDOWS = (20, 40, 60, 90, 120, 180, 252)
LOW_VOLATILITY_SELECTION_HORIZON = 63
LOW_VOLATILITY_ANCHOR_METHOD = "q10_minus_middle"
LOW_VOLATILITY_ANCHOR_BETA_NEUTRAL = True
LOW_VOLATILITY_ANCHOR_REBALANCE_DAYS = 63


# -------------------------
# DECLARED DECISION RULES
LOW_VOLATILITY_MIN_NET_SHARPE = 0.50
LOW_VOLATILITY_MIN_ALPHA_TSTAT = 1.96
LOW_VOLATILITY_MIN_LONG_WF_SHARPE = 0.25
LOW_VOLATILITY_MIN_LONG_WF_POSITIVE_RATE = 2 / 3
LOW_VOLATILITY_MIN_SHORT_WF_SHARPE = 0.00
LOW_VOLATILITY_MIN_SHORT_WF_POSITIVE_RATE = 0.55
LOW_VOLATILITY_MIN_PHASE_RETURN = 0.00
LOW_VOLATILITY_MIN_REGIME_RETURN = 0.00
LOW_VOLATILITY_MIN_25BPS_RETURN = 0.00
LOW_VOLATILITY_MIN_NEIGHBOUR_SUPPORT = 1
